PRIMARY: list[str]
SECONDARY: list[str]
BACKGROUND: list[str]
DETAIL: list[str]
INVERSE_BG: list[str]
DEFAULTS: dict[str, str]
SCHEMES: dict[str, dict[str, str]]
INVERSE_SCHEMES: dict[str, dict[str, str]]
COLORS: dict[str, dict[str, str]]
