class ExtractSVG:
    def __init__(self, svg_in: str) -> None: ...
    def check_svg(self, file: str, ex: bool = ...) -> bool: ...
    def extract_single(self) -> str: ...
    def extract_batch(self) -> dict[str, str]: ...

class WriteSVG:
    def __init__(self, out_svg: str) -> None: ...
    def write_single(self, text: str) -> None: ...
    def write_batch(self, svg_dict: dict[str, str]) -> None: ...
