from . import (
    BACKGROUND as BACKGROUND,
    DETAIL as DETAIL,
    INVERSE_BG as INVERSE_BG,
    PRIMARY as PRIMARY,
    SECONDARY as SECONDARY,
)

class Tint:
    def __init__(self, svg_in: str) -> None: ...
    def get_svg(self) -> str: ...
    def tint_colors(self, default: str, accent: str) -> None: ...
    def tint_scheme(self, variant: str, alt: str, difference: str) -> None: ...

class BatchTint:
    def __init__(self, svg_dict: dict[str, str]) -> None: ...
    def get_svg_dict(self) -> dict[str, str]: ...
    def tint_colors(self, default: str, accent: str) -> None: ...
    def tint_scheme(self, variant: str, alt: str, difference: str) -> None: ...
